#!/usr/bin/bash

#
# Copyright (c) 2022-2025, Sergey Bronnikov
# https://github.com/ligurio/litclock
#
# litclock script is released under the BSD 2-Clause license.
# See LICENSE file for details.
#
# SPDX-License-Identifier: BSD-2-Clause
#

set -e

PREFIX_DATA="/usr/local/share"

DEFAULT_LANG="ru"
DEFAULT_COLOR="\033[0;31m"
DISABLE_COLOR="\033[00m"
VERSION="0.2.0"

lang="${DEFAULT_LANG}"
ctime=""

usage() {
    echo "Usage: $0 [-p <path>] [-t <time>] [-l pt|ru|en] [-v]" 1>&2; exit 1;
}

while getopts ":p:t:l:v" o; do
    case "${o}" in
        p) quotes_file=${OPTARG} ;;
        t) ctime=${OPTARG} ;;
        l) lang=${OPTARG} ;;
        v) printf "litclock %s\n" ${VERSION} && exit 0 ;;
        *) usage ;;
    esac
done
shift $((OPTIND-1))

quotes_file="${PREFIX_DATA}/litclock/quotes_${lang}.csv"

printf_color() {
    local no_color_support="$NO_COLOR"
    local fmt="$1"
    local text="$2"
    if [ -z "${no_color_support}" ]; then
        printf "%b" "$DEFAULT_COLOR"
        # shellcheck disable=SC2059
        # shellcheck disable=SC2086
        printf $fmt "$text"
        printf "%b" "$DISABLE_COLOR"
    else
        printf "%s" "$time_words"
    fi
}

if ! [ -f "$quotes_file" ]; then
    echo "File $quotes_file is not found."
    exit 1
fi

if [ -z "${ctime}" ]; then
    ctime=$(date +"%H:%M")
fi

no_quote=1

IFS='|'

exec < "$quotes_file"
while read -r line
do
    read -r time time_words quote title author _ <<< "$line"
    if [ "$ctime" != "$time" ]; then
        continue
    fi
    no_quote=0
    quote_last=${quote#*"$time_words"}
    quote_first=${quote%%"$time_words"*}

    printf "\""
    printf "%s" "$quote_first"
    printf_color "%s" "$time_words"
    printf "%s" "$quote_last"
    printf "\"\n"
    printf " -- '%s', %s\n\n" "$title" "$author"

    break
done

if [ $no_quote -eq 1 ]; then
    if [ "X$lang" = "Xru" ]; then
        printf "Счастливые часов не наблюдают. -- 'Горе от ума', А.С. Грибоедов. (сейчас %s)\n" "$ctime"
    else
        printf "No quote. Time is %s.\n" "$ctime"
    fi
fi

exit 0
