#!/usr/bin/bash

#
# litclock 0.1.0
# Copyright (c) 2022, Sergey Bronnikov
# https://github.com/ligurio/litclock
#
# litclock script is released under the BSD 2-Clause license.
# See LICENSE file for details.
#
# SPDX-License-Identifier: BSD-2-Clause
#

set -eu

PREFIX_DATA="/usr/local/share"

DEFAULT_LANG="ru"
DEFAULT_COLOR="\033[0;31m"
DISABLE_COLOR="\e[0m"

lang="${DEFAULT_LANG}"
ctime=""

usage() {
	echo "Usage: $0 [-p <path>] [-t <time>] [-l ru|en] [-v]" 1>&2; exit 1;
}

while getopts ":p:t:l:v" o; do
    case "${o}" in
        p) quotes_file=${OPTARG} ;;
        t) ctime=${OPTARG} ;;
        l) lang=${OPTARG} ;;
		v) printf "litclock 0.1.0\n" && exit 0 ;;
        *) usage ;;
    esac
done
shift $((OPTIND-1))

quotes_file="${PREFIX_DATA}/litclock/quotes_${lang}.csv"

if ! [ -f "$quotes_file" ]; then
	echo "File $quotes_file is not found."
	exit 1
fi

if [ -z "${ctime}" ]; then
	ctime=$(date +"%H:%M")
fi

no_quote=1

IFS='|'

exec < "$quotes_file"
while read -r line
do
	read -r time quote_time_case quote title author sfw <<< "$line"
	if [ "$ctime" != "$time" ]; then
		continue
	fi
	no_quote=0
	quote_last=${quote#*"$quote_time_case"}
	quote_first=${quote%%"$quote_time_case"*}

	printf "\""
	printf "%s" "$quote_first"
	printf "%b" "$DEFAULT_COLOR"
	printf "%s" "$quote_time_case"
	printf "%b" "$DISABLE_COLOR"
	printf "%s" "$quote_last"
	printf "\"\n"
	printf " -- '%s', %s\n\n" "$title" "$author"

	break
done

if [ $no_quote -eq 1 ]; then
    if [ "X$lang" = "Xru" ]; then
        printf "Счастливые часов не наблюдают. (сейчас %s)\n" "$ctime"
    else
        printf "No quote. Time is %s.\n" "$ctime"
    fi
fi

exit 0
